# Numpy를 사용해야 하는 이유

1. List에 비해 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다.
2. C로 구현된 내부 반복문을 사용하기 때문에 파이썬의 반복문보다 속도가 빠르다.
3. Vectorized operation을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다.
4. 배열 인덱싱을 사용한 Query기능을 사용할 수 있다.

## 제약

1. 배열의 각각의 원소가 같은 자료형이어야 한다.
2. 원소의 개수를 바꾸려면 전부 재할당해야 한다.

In [2]:
import numpy as np

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(type(arr), arr)


<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]


# Vectorized Operation

In [7]:
# list case:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
2 * a + b

array([12, 24, 36])

In [11]:
a == 2

array([False,  True, False])

# Multi-dimensional Array

In [13]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
len(c)

2

In [19]:
len(c[0])

3

In [20]:
np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [23]:
c.ndim

2

In [22]:
c.shape

(2, 3)

In [24]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
a[0, 0]

0

In [26]:
a[0, 1]

1

In [27]:
a[-1, -1]

5

In [28]:
m = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])

In [29]:
m[1][2]

7

In [30]:
m[-1][-1]

14

In [40]:
m[1,1:3]

array([6, 7])

In [39]:
m[1:,2]

array([ 7, 12])

In [41]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

# Array Indexing

- idx가 boolean 배열일 경우, True에 해당하는 a의 원소로만 새롭게 구성한다.
- idx가 integer 배열일 경우, idx의 각 원소가 나타내는 것은 해당 위치에 넣을 a의 원소의 위치이다.

In [45]:
a = np.array([x for x in range(0, 10)])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [46]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [47]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [49]:
a = np.array([x * 11 for x in range(1, 10)])
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [51]:
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [54]:
idx = np.array([0, 0, 0, 8, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 99, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [57]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [58]:
x = np.array([x for x in range(1, 21)])

In [59]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [60]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [65]:
x[(x % 3 == 0) | (x % 4 == 1)]

array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18])