In [1]:
import numpy as np

# Numpy Datatype

In [2]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [3]:
x = np.array([1.0, 2., 3.])
x.dtype

dtype('float64')

In [5]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [6]:
x = np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [7]:
x[0] + x[1]

3.0

In [8]:
x = np.array([1, 2, 3], dtype = 'U')
x.dtype

dtype('<U1')

In [9]:
x[0] + x[1]

'12'

In [10]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

/var/folders/lr/jj1kxjwn315g3cjyb46358l80000gn/T/ipykernel_25434/2068585620.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
/var/folders/lr/jj1kxjwn315g3cjyb46358l80000gn/T/ipykernel_25434/2068585620.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [12]:
np.log(0)

/var/folders/lr/jj1kxjwn315g3cjyb46358l80000gn/T/ipykernel_25434/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [13]:
np.exp(-np.inf)

0.0

# 배열 생성

- zeros, ones

- zeros_like, ones_like

- empty

- arange

- linspace, logspace

In [14]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [15]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
c = np.zeros((5, 2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [17]:
d = np.zeros(5, dtype = 'U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [18]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [19]:
e = np.ones((2, 3, 4), dtype = 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [21]:
f = np.ones_like(b, dtype = 'f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [22]:
g = np.empty((4, 3))
g

array([[-1.49166815e-154, -1.49457543e-154,  3.95252517e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 3.50977866e+064, -1.49166815e-154,  3.11108794e+231]])

In [23]:
np.arange(10) # list의 range와 같이, 특정한 규칙에 따라 증가하는 수열을 만든다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
np.linspace(0, 100, 5) # 5개로 분할

array([  0.,  25.,  50.,  75., 100.])

In [27]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [31]:
np.logspace(0.1, 0.25, 4)

array([1.25892541, 1.41253754, 1.58489319, 1.77827941])

# 전치 연산

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 배열의 크기 변형

In [34]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a.reshape(3, -1) # -1의 자리는 자동 계산됨

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## flatten() : flat

In [39]:
a.flatten() # 값을 복사해서 새로운 배열을 만듦

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.ravel() # 얕은 복사가 이루어지기 때문에 값을 공유함

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
onedimension = np.arange(5)
onedimension

array([0, 1, 2, 3, 4])

In [44]:
two_5by1 = onedimension.reshape(5, 1)
two_5by1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [45]:
two_1by5 = onedimension.reshape(1, 5)
two_1by5

array([[0, 1, 2, 3, 4]])

## newaxis : 차원 추가

In [46]:
onedimension[:, np.newaxis] # 차원 증가

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [47]:
onedimension[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

# 배열 연결

## hstack : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결 (horizontal)

In [48]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

## vstack : 열의 수가 같은 두 개 이상의 배열을 아래로 연결 (Vertical)

In [49]:
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## dstack : 크기가 정확히 같은 두 배열을 깊이 방향으로 연결 (Depth)

In [56]:
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))

In [57]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

## stack : 지정한 방향으로 차원 생성

- axis = 0 (default) : 모든 원소를 감싸는 바깥에 차원 생성
- axis = 1 : depth 1에서 차원 생성
- axis = 2 : 2차원 배열의 경우, dstack과 같은 결과


In [62]:
c = np.stack([c1, c2], axis= 0)
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [64]:
c = np.stack([c1, c2], axis= 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [65]:
c = np.stack([c1, c2], axis= 2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

## indexer : 소괄호 대신에 대괄호를 이용해 호출하는 메서드

## r_ : hstack과 같이, 옆으로 (row) 배열을 잇는다.

In [68]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

## c_ : 배열의 차원을 증가시킨 후 좌우로 연결한다. (1차원 배열을 연결하면 2차원 배열이 된다.)

In [70]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

## tile : 동일한 배열을 반복하여 연결한다.

In [73]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [72]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [92]:
np.tile(np.vstack([np.c_[np.zeros((3, 3)), np.ones((3, 2))], np.array([x * 10 for x in range(1, 16)]).reshape(3, -1)]), (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

# meshgrid : 2차원 그리드 포인트

In [106]:
x = np.arange(-2, 3)
x

array([-2, -1,  0,  1,  2])

In [104]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [107]:
X, Y = np.meshgrid(x, y)

In [108]:
X

array([[-2, -1,  0,  1,  2],
       [-2, -1,  0,  1,  2],
       [-2, -1,  0,  1,  2]])

In [109]:
Y

array([[-1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1]])

In [110]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(-2, -1), (-1, -1), (0, -1), (1, -1), (2, -1)],
 [(-2, 0), (-1, 0), (0, 0), (1, 0), (2, 0)],
 [(-2, 1), (-1, 1), (0, 1), (1, 1), (2, 1)]]