# Vectorized operation

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [5]:
a == b

array([False,  True, False,  True])

In [6]:
a >= b

array([False,  True,  True,  True])

In [7]:
np.all(a == b)

False

In [8]:
np.all(a == c)

True

In [9]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [10]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [11]:
np.log(x + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [12]:
10 ** a

array([   10,   100,  1000, 10000])

# 스칼라와 벡터 / 행렬의 곱셈

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [16]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 브로드캐스팅
> 크기가 다른 벡터 간의 연산이 가능하도록, 자동으로 크기를 확장해주는 기능

In [18]:
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [19]:
y = np.arange(4)
x + y

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [21]:
z = np.ones((5, 5))
x + z

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

# 차원 축소 연산

In [23]:
x = np.arange(4) + 1
x

array([1, 2, 3, 4])

In [24]:
print(np.sum(x), x.sum())

10 10


In [25]:
print(x.max(), x.min(), x.argmin(), x.argmax(), x.mean(), np.median(x))

4 1 0 3 2.5 2.5


In [27]:
b = np.array([True, True, False])
b.any(), b.all()

(True, False)

## axis 인수

In [29]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [30]:
x.sum()

6

In [31]:
x.sum(axis = 0)

array([3, 3])

In [32]:
x.sum(axis = 1)

array([2, 4])

In [37]:
x = np.arange(1., 60., 2.).reshape((5, 6))
x

array([[ 1.,  3.,  5.,  7.,  9., 11.],
       [13., 15., 17., 19., 21., 23.],
       [25., 27., 29., 31., 33., 35.],
       [37., 39., 41., 43., 45., 47.],
       [49., 51., 53., 55., 57., 59.]])

In [41]:
print(x.max(), x.sum(axis = 1), x.max(axis = 1), x.mean(axis = 0), x.min(axis = 0))

59.0 [ 36. 108. 180. 252. 324.] [11. 23. 35. 47. 59.] [25. 27. 29. 31. 33. 35.] [ 1.  3.  5.  7.  9. 11.]


# 정렬 : sort, argsort

- axis = -1 : 가장 안쪽 차원에 대해 정렬한다.
- axis = 0 : 각각의 행 간 정렬한다.
- axis = 1 : 각각의 열 간 정렬한다.

In [42]:
a = np.array([[4, 3, 5, 7], [1, 12, 11, 9], [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [44]:
np.sort(a) # axis = -1 or 1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [45]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

## 작은 순의 순서를 얻고 싶다면 argsort

In [46]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [47]:
a[j]

array([12, 25, 38, 42])

In [48]:
np.sort(a)

array([12, 25, 38, 42])

In [50]:
score = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [54]:
score[1].argsort()

array([0, 3, 1, 2])

In [63]:
# 테이블을 정렬하는 방법: T, argsort로 sort, T
score.T[score[1].argsort()].T

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])