In [1]:
import numpy as np
from numpy import random as rd

# 난수 발생과 카운팅

In [4]:
# 시드 설정
rd.seed(0)

In [3]:
# 난수 5개 발생
rd.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

# 데이터의 순서 바꾸기

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
rd.shuffle(x) # 자체 변환 함수
x

array([9, 4, 7, 3, 2, 6, 1, 8, 5, 0])

# 데이터 샘플링

In [11]:
np.random.choice(5, 5, replace = False) # arange(5)의 integer array에서 5개를 중복하지 않고 추출

array([4, 2, 3, 1, 0])

In [13]:
np.random.choice([1,2,5,6,10,11,15,16], 7, replace=True) # 주어진 array에서 7개를 중복해 추출

array([15,  6,  5, 16, 10,  5,  1])

In [14]:
np.random.choice(5, 10)

array([0, 4, 0, 4, 1, 4, 1, 2, 2, 0])

In [15]:
np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0])

array([3, 0, 3, 3, 2, 2, 3, 3, 2, 0])

# 백야극광 가챠 시뮬레이터

In [2]:
pickup = 0
non_pickup = 0
gacha = 0
p = [0.01, 0.01, 0.98]
s = ['6성 픽업', '6성 픽뚫', '꽝']

In [81]:
res = np.random.choice(s, 10, replace= True, p = p)
pickup += len(res[res == '6성 픽업'])
non_pickup += len(res[res == '6성 픽뚫'])
gacha += 10
res

array(['꽝', '꽝', '꽝', '꽝', '꽝', '꽝', '꽝', '꽝', '꽝', '꽝'], dtype='<U5')

In [35]:
print('6성: {}, 6성 픽업: {}, 총 {}연차'.format(pickup + non_pickup, pickup, gacha))

6성: 10, 6성 픽업: 6, 총 290연차


# 난수 생성

- rand : 0 ~ 1 사이의 가우시안 분포
- randn : 표준 정규 분포
- randint : 가우시안 분포의 정수

In [290]:
rd.rand(10)

array([0.88481189, 0.45285558, 0.93065546, 0.02991454, 0.71945011,
       0.95535789, 0.46956673, 0.25385505, 0.65150422, 0.38197408])

In [291]:
rd.randn(10)

array([-1.21493624, -1.37548499, -1.22877374, -2.21033979,  0.49677125,
       -0.93928637,  0.49575515,  0.71984916, -1.19177033, -0.28705101])

In [294]:
rd.randint(low = 5, high = 10, size = 4)

array([7, 7, 9, 5])

In [300]:
rd.choice([True, False], 10)

array([ True, False, False, False,  True,  True, False, False,  True,
        True])

In [301]:
rd.choice(np.arange(6) + 1, 100).mean()

3.57

In [308]:
price = 10000
diff = rd.randn(5)
print(diff)
for day in range(5):
    price = price * (1 + diff[day] * 0.01)
    diff[day] = price
print(diff)

[ 1.32148654 -2.44851723 -0.61521139 -0.64625746 -1.05509962]
[10132.14865395  9884.06124798  9823.25337788  9759.76987059
  9656.79457577]


# 정수 데이터 카운팅

## unique

- 중복된 값을 제거한 ndarray 반환
- return_counts를 설정해주면 반환된 ndarray에 각 인덱스에 해당하는 등장횟수를 기록한 또 다른 ndarray도 함께 반환

In [309]:
np.unique([11, 11, 2, 2, 34, 34, 35])

array([ 2, 11, 34, 35])

In [312]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts = True)
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

## bincount

In [313]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])